### ISSUE TITLE
does project fit any fpga board?

### ISSUE THREAD

**Issue by 1847123212** [hansfbaier/ch569-usb3-hspi-bridge#1]
does project fit any fpga board, and has any fpga test code? 
i found this project, https://github.com/hansfbaier/ch569-hspi-fpga, but it looks like an python project or python run on fpga?
thx

**Comment by hansfbaier** [comment]
Yes it uses a python based hardware des description language called amaranth (previously nmigen). It runs on my self designed board, but can easily adapted to other boards.

**Comment by hansfbaier** [comment]
https://github.com/RobertBaruch/nmigen-tutorial
https://libre-soc.org/docs/learning_nmigen/
